# This is a basic workflow to help you get started with Actions

name: Pull Request

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  unit-tests:
    name: unit tests
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Restore node_modules
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - if: steps.cache-node_modules.outputs.cache-hit != 'true'
        name: Install dependencies
        run: npm install
      - name: Unit Test
        run: npm test

