name: Release
on:
  push:
    branches: [main, beta]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: https://npm.pkg.github.com/
          scope: "@hyphen"
      - name: install dependencies
        run: npm install
      - name: test
        run: npm test
      - name: build
        run: npm run build
      - name: Release to Github Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: npm run semantic-release
